blank_issues_enabled: false
contact_links:
  - name: Declarative Automation Bundles Documentation
    url: https://docs.databricks.com/aws/en/dev-tools/bundles/
    about: Official Databricks documentation for Automation Bundles
  - name: Questions & Discussion
    url: https://github.com/vmariiechko/databricks-bundle-template/discussions/categories/q-a
    about: Ask questions and get help from the community
